# np.rot90()

A visual walkthrough [`numpy.rot90()`](https://numpy.org/doc/stable/reference/generated/numpy.rot90.html) function used in this minimal implementation of the 2048 game.

In [1]:
import numpy as np

In [2]:
# Generate a feasible 2048 board state as a numpy array
x = np.array([2,0,0,2, 0,0,0,0, 0,2,4,4, 8,0,8,8]).reshape((4,4))
x

array([[2, 0, 0, 2],
       [0, 0, 0, 0],
       [0, 2, 4, 4],
       [8, 0, 8, 8]])

## Visualising Rotations

In [3]:
# Standard 90 deg rotation
np.rot90(x)

array([[2, 0, 4, 8],
       [0, 0, 4, 8],
       [0, 0, 2, 0],
       [2, 0, 0, 8]])

In [4]:
import sys
sys.path.append('..')

from utils import actions

# 2048 game actions
action_annotations = {
    "W": "UP",
    "A": "LEFT",
    "S": "DOWN",
    "D": "RIGHT"
}

# Visualisation of rotation for each move
list(zip([f"{action_annotations[action]} ({action})" for action in actions.keys()], [np.rot90(x, k=action) for action in range(4)]))

[('UP (W)',
  array([[2, 0, 0, 2],
         [0, 0, 0, 0],
         [0, 2, 4, 4],
         [8, 0, 8, 8]])),
 ('LEFT (A)',
  array([[2, 0, 4, 8],
         [0, 0, 4, 8],
         [0, 0, 2, 0],
         [2, 0, 0, 8]])),
 ('DOWN (S)',
  array([[8, 8, 0, 8],
         [4, 4, 2, 0],
         [0, 0, 0, 0],
         [2, 0, 0, 2]])),
 ('RIGHT (D)',
  array([[8, 0, 0, 2],
         [0, 2, 0, 0],
         [8, 4, 0, 0],
         [8, 4, 0, 2]]))]

In [5]:
action = "A"

board = np.copy(x)
print(f"board:\n{board}\n")
rotated_board = np.rot90(np.copy(board), -actions[action])
print(f"rotated_board:\n{rotated_board}")

board:
[[2 0 0 2]
 [0 0 0 0]
 [0 2 4 4]
 [8 0 8 8]]

rotated_board:
[[2 0 0 2]
 [0 0 0 0]
 [0 2 4 4]
 [8 0 8 8]]


## Visualising 2048 Actions

In [6]:
i = 0

row = rotated_board[i, :]
print(f"'{action_annotations[action]}' slice:\n{row}\n")
print(f"non zero row: {row[row != 0]}")
print(f"zero padding: {np.zeros(4 - np.count_nonzero(row))}\n")
row = np.concatenate((row[row != 0], np.zeros(4 - np.count_nonzero(row))))
print(f"'{action_annotations[action]}' slide action:\n{row}\n")

'LEFT' slice:
[2 0 0 2]

non zero row: [2 2]
zero padding: [0. 0.]

'LEFT' slide action:
[2. 2. 0. 0.]



In [7]:
for j in range(3):
    if row[j] == row[j + 1]:
        row[j] *= 2
        row[j + 1] = 0
print(f"aggregated row: {row}\n")

row = row[row != 0]
row = np.concatenate((row, np.zeros(4 - len(row))))
rotated_board[i, :] = row
print(f"slice update:\n{rotated_board}")

aggregated row: [4. 0. 0. 0.]

slice update:
[[4 0 0 0]
 [0 0 0 0]
 [0 2 4 4]
 [8 0 8 8]]


In [8]:
i = 1

row = rotated_board[i, :]
print(f"'{action_annotations[action]}' slice:\n{row}\n")
print(f"non zero row: {row[row != 0]}")
print(f"zero padding: {np.zeros(4 - np.count_nonzero(row))}\n")
row = np.concatenate((row[row != 0], np.zeros(4 - np.count_nonzero(row))))
print(f"'{action_annotations[action]}' slide action:\n{row}\n")

for j in range(3):
    if row[j] == row[j + 1]:
        row[j] *= 2
        row[j + 1] = 0
print(f"aggregated row: {row}\n")

row = row[row != 0]
row = np.concatenate((row, np.zeros(4 - len(row))))
rotated_board[i, :] = row
print(f"slice update:\n{rotated_board}")

'LEFT' slice:
[0 0 0 0]

non zero row: []
zero padding: [0. 0. 0. 0.]

'LEFT' slide action:
[0. 0. 0. 0.]

aggregated row: [0. 0. 0. 0.]

slice update:
[[4 0 0 0]
 [0 0 0 0]
 [0 2 4 4]
 [8 0 8 8]]


In [9]:
i = 2

row = rotated_board[i, :]
print(f"'{action_annotations[action]}' slice:\n{row}\n")
print(f"non zero row: {row[row != 0]}")
print(f"zero padding: {np.zeros(4 - np.count_nonzero(row))}\n")
row = np.concatenate((row[row != 0], np.zeros(4 - np.count_nonzero(row))))
print(f"'{action_annotations[action]}' slide action:\n{row}\n")

for j in range(3):
    if row[j] == row[j + 1]:
        row[j] *= 2
        row[j + 1] = 0
print(f"aggregated row: {row}\n")

row = row[row != 0]
row = np.concatenate((row, np.zeros(4 - len(row))))
rotated_board[i, :] = row
print(f"slice update:\n{rotated_board}")

'LEFT' slice:
[0 2 4 4]

non zero row: [2 4 4]
zero padding: [0.]

'LEFT' slide action:
[2. 4. 4. 0.]

aggregated row: [2. 8. 0. 0.]

slice update:
[[4 0 0 0]
 [0 0 0 0]
 [2 8 0 0]
 [8 0 8 8]]


In [10]:
i = 3

row = rotated_board[i, :]
print(f"'{action_annotations[action]}' slice:\n{row}\n")
print(f"non zero row: {row[row != 0]}")
print(f"zero padding: {np.zeros(4 - np.count_nonzero(row))}\n")
row = np.concatenate((row[row != 0], np.zeros(4 - np.count_nonzero(row))))
print(f"'{action_annotations[action]}' slide action:\n{row}\n")

for j in range(3):
    if row[j] == row[j + 1]:
        row[j] *= 2
        row[j + 1] = 0
print(f"aggregated row: {row}\n")

row = row[row != 0]
row = np.concatenate((row, np.zeros(4 - len(row))))
rotated_board[i, :] = row
print(f"slice update:\n{rotated_board}")

'LEFT' slice:
[8 0 8 8]

non zero row: [8 8 8]
zero padding: [0.]

'LEFT' slide action:
[8. 8. 8. 0.]

aggregated row: [16.  0.  8.  0.]

slice update:
[[ 4  0  0  0]
 [ 0  0  0  0]
 [ 2  8  0  0]
 [16  8  0  0]]


In [11]:
board = np.array([2,0,0,2, 0,0,0,0, 0,2,4,4, 8,0,8,8]).reshape((4,4))
print(f"board:\n{board}\n")
rotated_board = np.rot90(np.array([2,0,0,2, 0,0,0,0, 0,2,4,4, 8,0,8,8]).reshape((4,4)), -actions[action])

for i in range(4):
    row = rotated_board[i, :]
    row = np.concatenate((row[row != 0], np.zeros(4 - np.count_nonzero(row))))

    for j in range(3):
        if row[j] == row[j + 1]:
            row[j] *= 2
            row[j + 1] = 0

    row = row[row != 0]
    row = np.concatenate((row, np.zeros(4 - len(row))))
    rotated_board[i, :] = row

print(f"rotated_board:\n{rotated_board}")

board:
[[2 0 0 2]
 [0 0 0 0]
 [0 2 4 4]
 [8 0 8 8]]

rotated_board:
[[ 4  0  0  0]
 [ 0  0  0  0]
 [ 2  8  0  0]
 [16  8  0  0]]


In [12]:
updated_board = np.rot90(rotated_board, actions[action])
print(f"('{action_annotations[action]}') updated_board:\n{updated_board}")

('LEFT') updated_board:
[[ 4  0  0  0]
 [ 0  0  0  0]
 [ 2  8  0  0]
 [16  8  0  0]]
